export let developers: Array<Developer> = [
  {
    id: 0,
    developerName: "West Coast Software",
    contactEmail: "West Coast Software@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 1,
    developerName: "Soma Games",
    contactEmail: "Soma Games@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 2,
    developerName: "Prettygreat Pty",
    contactEmail: "Prettygreat Pty@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 3,
    developerName: "Oasis Games||Geronimo Interactive",
    contactEmail: "Oasis Games||Geronimo Interactive@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 4,
    developerName: "Viking Tao",
    contactEmail: "Viking Tao@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 5,
    developerName: "Alexander Ponomariov",
    contactEmail: "Alexander Ponomariov@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 6,
    developerName: "David Szymanski",
    contactEmail: "David Szymanski@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 7,
    developerName: "woof",
    contactEmail: "woof@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 8,
    developerName: "alegaroficial",
    contactEmail: "alegaroficial@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 9,
    developerName: "Atte Okkonen",
    contactEmail: "Atte Okkonen@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 10,
    developerName: "Dansodic",
    contactEmail: "Dansodic@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 11,
    developerName: "Alistair Aitcheson",
    contactEmail: "Alistair Aitcheson@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 12,
    developerName: "Jayson Musson",
    contactEmail: "Jayson Musson@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 13,
    developerName: "Croteam",
    contactEmail: "Croteam@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 14,
    developerName: "Bizarre Monkey",
    contactEmail: "Bizarre Monkey@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 15,
    developerName: "Eufrasio",
    contactEmail: "Eufrasio@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 16,
    developerName: "11th Dimension Entertainment",
    contactEmail: "11th Dimension Entertainment@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 17,
    developerName: "Dark Wall Games",
    contactEmail: "Dark Wall Games@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 18,
    developerName: "Dermot",
    contactEmail: "Dermot@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 19,
    developerName: "MAVW",
    contactEmail: "MAVW@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 20,
    developerName: "VikkiRuttle",
    contactEmail: "VikkiRuttle@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 21,
    developerName: "IanAnimated",
    contactEmail: "IanAnimated@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 22,
    developerName: "Jordan Oloman",
    contactEmail: "Jordan Oloman@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 23,
    developerName: "Mindillusion",
    contactEmail: "Mindillusion@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 24,
    developerName: "Dark Gaia Studios",
    contactEmail: "Dark Gaia Studios@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 25,
    developerName: "B0pt1K",
    contactEmail: "B0pt1K@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 26,
    developerName: "ciderwrath",
    contactEmail: "ciderwrath@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 27,
    developerName: "Plug In Digital",
    contactEmail: "Plug In Digital@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 28,
    developerName: "PC",
    contactEmail: "PC@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 29,
    developerName: "Billy Slang",
    contactEmail: "Billy Slang@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 30,
    developerName: "reel_big_kris",
    contactEmail: "reel_big_kris@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 31,
    developerName: "FelixBlobDev",
    contactEmail: "FelixBlobDev@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 32,
    developerName: "Leonid Pilchin",
    contactEmail: "Leonid Pilchin@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 33,
    developerName: "Game-Labs",
    contactEmail: "Game-Labs@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 34,
    developerName: "Troy-Martens",
    contactEmail: "Troy-Martens@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 35,
    developerName: "Solomon Fletcher",
    contactEmail: "Solomon Fletcher@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 36,
    developerName: "Mauricio Felippe",
    contactEmail: "Mauricio Felippe@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 37,
    developerName: "indspenceable",
    contactEmail: "indspenceable@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 38,
    developerName: "coffeemuggames",
    contactEmail: "coffeemuggames@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 39,
    developerName: "Artefact",
    contactEmail: "Artefact@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 40,
    developerName: "corpsmoderne",
    contactEmail: "corpsmoderne@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 41,
    developerName: "Xand",
    contactEmail: "Xand@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 42,
    developerName: "bhimz",
    contactEmail: "bhimz@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 43,
    developerName: "Borealys Games",
    contactEmail: "Borealys Games@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 44,
    developerName: "Handle",
    contactEmail: "Handle@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 45,
    developerName: "Peaksel",
    contactEmail: "Peaksel@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 46,
    developerName: "cottontrek",
    contactEmail: "cottontrek@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 47,
    developerName: "Lethargic in the Park",
    contactEmail: "Lethargic in the Park@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 48,
    developerName: "goofanader||adeeda",
    contactEmail: "goofanader||adeeda@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 49,
    developerName: "Vault of Tears Games",
    contactEmail: "Vault of Tears Games@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 50,
    developerName: "seizethedia",
    contactEmail: "seizethedia@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 51,
    developerName: "Crimson Duck Studios",
    contactEmail: "Crimson Duck Studios@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 52,
    developerName: "BlueWinds",
    contactEmail: "BlueWinds@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 53,
    developerName: "Headup Games||Pine Studio",
    contactEmail: "Headup Games||Pine Studio@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 54,
    developerName: "[astro station]",
    contactEmail: "[astro station]@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 55,
    developerName: "Jana Games Studios",
    contactEmail: "Jana Games Studios@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 56,
    developerName: "Pigmeat",
    contactEmail: "Pigmeat@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 57,
    developerName: "Roman",
    contactEmail: "Roman@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 58,
    developerName: "britzl",
    contactEmail: "britzl@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 59,
    developerName: "Rahul Martin",
    contactEmail: "Rahul Martin@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 60,
    developerName: "FMinuzzi",
    contactEmail: "FMinuzzi@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 61,
    developerName: "autophagy",
    contactEmail: "autophagy@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 62,
    developerName: "FafaStudio",
    contactEmail: "FafaStudio@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 63,
    developerName: "mutantcodpiece",
    contactEmail: "mutantcodpiece@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 64,
    developerName: "TeamCrew",
    contactEmail: "TeamCrew@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 65,
    developerName: "onemrbean",
    contactEmail: "onemrbean@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 66,
    developerName: "LadyWilliam",
    contactEmail: "LadyWilliam@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 67,
    developerName: "ClayByte",
    contactEmail: "ClayByte@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 68,
    developerName: "TakiTonfa",
    contactEmail: "TakiTonfa@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 69,
    developerName: "AaronOldenburg",
    contactEmail: "AaronOldenburg@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 70,
    developerName: "serioussam909||The Embraced One",
    contactEmail: "serioussam909||The Embraced One@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 71,
    developerName: "Maku Animeda",
    contactEmail: "Maku Animeda@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 72,
    developerName: "Oscar Brittain",
    contactEmail: "Oscar Brittain@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 73,
    developerName: "Fabulas Games",
    contactEmail: "Fabulas Games@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 74,
    developerName: "One Man Army Games",
    contactEmail: "One Man Army Games@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 75,
    developerName: "Benn Powell",
    contactEmail: "Benn Powell@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 76,
    developerName: "bippinbits",
    contactEmail: "bippinbits@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 77,
    developerName: "Aaron Santiago",
    contactEmail: "Aaron Santiago@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 78,
    developerName: "Dealey",
    contactEmail: "Dealey@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 79,
    developerName: "Brevitius",
    contactEmail: "Brevitius@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 80,
    developerName: "William Baldwin",
    contactEmail: "William Baldwin@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 81,
    developerName: "catapultfish",
    contactEmail: "catapultfish@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 82,
    developerName: "joebain",
    contactEmail: "joebain@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 83,
    developerName: "Team Gormless",
    contactEmail: "Team Gormless@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 84,
    developerName: "Sean Bouchard||Martzi",
    contactEmail: "Sean Bouchard||Martzi@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 85,
    developerName: "Kalypso Media||Kite Games",
    contactEmail: "Kalypso Media||Kite Games@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 86,
    developerName: "LvlAppStudio",
    contactEmail: "LvlAppStudio@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 87,
    developerName: "Case1",
    contactEmail: "Case1@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 88,
    developerName: "Dadcore Digital",
    contactEmail: "Dadcore Digital@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 89,
    developerName: "Xenotrope Games",
    contactEmail: "Xenotrope Games@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 90,
    developerName: "Alfreddy",
    contactEmail: "Alfreddy@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 91,
    developerName: "retrorocketeers",
    contactEmail: "retrorocketeers@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 92,
    developerName: "Kappa.b",
    contactEmail: "Kappa.b@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 93,
    developerName: "Slothy Labs",
    contactEmail: "Slothy Labs@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 94,
    developerName: "Aéronie",
    contactEmail: "Aéronie@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 95,
    developerName: "Pedro Paiva",
    contactEmail: "Pedro Paiva@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 96,
    developerName: "nomalles",
    contactEmail: "nomalles@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 97,
    developerName: "sgadrat",
    contactEmail: "sgadrat@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 98,
    developerName: "MDVGames",
    contactEmail: "MDVGames@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 99,
    developerName: "Richard_Daskas",
    contactEmail: "Richard_Daskas@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 100,
    developerName: "konoe",
    contactEmail: "konoe@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 101,
    developerName: "Outgunned Games",
    contactEmail: "Outgunned Games@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 102,
    developerName: "Cosmic Adventure Squad",
    contactEmail: "Cosmic Adventure Squad@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 103,
    developerName: "Mr Frog",
    contactEmail: "Mr Frog@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 104,
    developerName: "Lethargic in the Park",
    contactEmail: "Lethargic in the Park@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 105,
    developerName: "Gobbo Games",
    contactEmail: "Gobbo Games@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 106,
    developerName: "melessthanthree",
    contactEmail: "melessthanthree@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 107,
    developerName: "kyuu",
    contactEmail: "kyuu@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 108,
    developerName: "ClÃ©ment Duquesne",
    contactEmail: "ClÃ©ment Duquesne@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 109,
    developerName: "TomCooper3D",
    contactEmail: "TomCooper3D@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 110,
    developerName: "TylerC",
    contactEmail: "TylerC@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 111,
    developerName: "Rainssong",
    contactEmail: "Rainssong@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 112,
    developerName: "Artylo",
    contactEmail: "Artylo@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 113,
    developerName: "FarmerGnome",
    contactEmail: "FarmerGnome@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 114,
    developerName: "CowThing",
    contactEmail: "CowThing@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 115,
    developerName: "bunnybreaker",
    contactEmail: "bunnybreaker@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 116,
    developerName: "Tinkertainment",
    contactEmail: "Tinkertainment@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 117,
    developerName: "1StupidRat - Toxic Sasquatch",
    contactEmail: "1StupidRat - Toxic Sasquatch@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 118,
    developerName: "Rango",
    contactEmail: "Rango@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 119,
    developerName: "Intertum",
    contactEmail: "Intertum@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 120,
    developerName: "Alex T. Colombini",
    contactEmail: "Alex T. Colombini@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 121,
    developerName: "Folz",
    contactEmail: "Folz@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 122,
    developerName: "xXarabongXx",
    contactEmail: "xXarabongXx@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 123,
    developerName: "rarelikeaunicorn",
    contactEmail: "rarelikeaunicorn@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 124,
    developerName: "donboody",
    contactEmail: "donboody@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 125,
    developerName: "Brave Rabbit Games",
    contactEmail: "Brave Rabbit Games@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 126,
    developerName: "AaronB",
    contactEmail: "AaronB@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 127,
    developerName: "Vonnbit",
    contactEmail: "Vonnbit@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 128,
    developerName: "Jusiv",
    contactEmail: "Jusiv@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 129,
    developerName: "Leggy",
    contactEmail: "Leggy@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 130,
    developerName: "DanielSnd",
    contactEmail: "DanielSnd@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 131,
    developerName: "Gero",
    contactEmail: "Gero@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 132,
    developerName: "Jay Yabsley",
    contactEmail: "Jay Yabsley@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 133,
    developerName: "Bret Sepulveda",
    contactEmail: "Bret Sepulveda@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 134,
    developerName: "AmelieBy",
    contactEmail: "AmelieBy@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 135,
    developerName: "Milestone",
    contactEmail: "Milestone@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 136,
    developerName: "POLIMI Game Collective",
    contactEmail: "POLIMI Game Collective@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 137,
    developerName: "Zircona Works",
    contactEmail: "Zircona Works@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 138,
    developerName: "Old School Entertainment",
    contactEmail: "Old School Entertainment@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 139,
    developerName: "tomqz",
    contactEmail: "tomqz@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 140,
    developerName: "William John Holly",
    contactEmail: "William John Holly@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 141,
    developerName: "bunaguchi",
    contactEmail: "bunaguchi@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 142,
    developerName: "Studio Vetea",
    contactEmail: "Studio Vetea@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 143,
    developerName: "Artifice Machine",
    contactEmail: "Artifice Machine@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 144,
    developerName: "FrozenRose",
    contactEmail: "FrozenRose@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 145,
    developerName: "Juan Barba",
    contactEmail: "Juan Barba@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 146,
    developerName: "Andrew Ryan Henke",
    contactEmail: "Andrew Ryan Henke@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 147,
    developerName: "charon@ss",
    contactEmail: "charon@ss@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 148,
    developerName: "minuo",
    contactEmail: "minuo@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 149,
    developerName: "m-lckr",
    contactEmail: "m-lckr@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 150,
    developerName: "DavidPixel",
    contactEmail: "DavidPixel@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 151,
    developerName: "Jerementor",
    contactEmail: "Jerementor@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 152,
    developerName: "anna anthropy",
    contactEmail: "anna anthropy@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 153,
    developerName: "CerebralTiger",
    contactEmail: "CerebralTiger@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 154,
    developerName: "Mysli",
    contactEmail: "Mysli@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 155,
    developerName: "Star Vault",
    contactEmail: "Star Vault@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 156,
    developerName: "KevKev",
    contactEmail: "KevKev@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 157,
    developerName: "TheOtherGuy",
    contactEmail: "TheOtherGuy@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 158,
    developerName: "P1X",
    contactEmail: "P1X@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 159,
    developerName: "josefnpat",
    contactEmail: "josefnpat@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 160,
    developerName: "justinbieshaar",
    contactEmail: "justinbieshaar@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 161,
    developerName: "Adam Rezich",
    contactEmail: "Adam Rezich@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 162,
    developerName: "Brox||Station 437",
    contactEmail: "Brox||Station 437@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 163,
    developerName: "Matthew_Moore",
    contactEmail: "Matthew_Moore@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 164,
    developerName: "Jem Smith",
    contactEmail: "Jem Smith@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 165,
    developerName: "Reval Indie House",
    contactEmail: "Reval Indie House@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 166,
    developerName: "Subvert Games",
    contactEmail: "Subvert Games@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 167,
    developerName: "Martin Cohen",
    contactEmail: "Martin Cohen@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 168,
    developerName: "feversuperstar",
    contactEmail: "feversuperstar@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 169,
    developerName: "GameChump",
    contactEmail: "GameChump@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 170,
    developerName: "Benal",
    contactEmail: "Benal@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 171,
    developerName: "Jason Payne",
    contactEmail: "Jason Payne@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 172,
    developerName: "BathPirate",
    contactEmail: "BathPirate@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 173,
    developerName: "eriban",
    contactEmail: "eriban@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 174,
    developerName: "TeamTacoCat",
    contactEmail: "TeamTacoCat@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 175,
    developerName: "Trend Redaktions- und Verlagsgesellschaft mbH",
    contactEmail: "Trend Redaktions- und Verlagsgesellschaft mbH@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 176,
    developerName: "nemonio",
    contactEmail: "nemonio@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 177,
    developerName: "SpaceDogGames",
    contactEmail: "SpaceDogGames@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 178,
    developerName: "KasSanity||Heather Robertson",
    contactEmail: "KasSanity||Heather Robertson@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 179,
    developerName: "Aegon Games",
    contactEmail: "Aegon Games@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 180,
    developerName: "renato_grottesi",
    contactEmail: "renato_grottesi@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 181,
    developerName: "Wildgrass",
    contactEmail: "Wildgrass@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 182,
    developerName: "Franklin's Ghost",
    contactEmail: "Franklin's Ghost@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 183,
    developerName: "Usamahsnakeeater",
    contactEmail: "Usamahsnakeeater@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 184,
    developerName: "MonsterJail",
    contactEmail: "MonsterJail@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 185,
    developerName: "Martian's Parlor Entertainment",
    contactEmail: "Martian's Parlor Entertainment@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 186,
    developerName: "Gravity Sketch",
    contactEmail: "Gravity Sketch@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 187,
    developerName: "SlimeG",
    contactEmail: "SlimeG@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 188,
    developerName: "shabby",
    contactEmail: "shabby@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 189,
    developerName: "ProdigalSon||Drums",
    contactEmail: "ProdigalSon||Drums@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 190,
    developerName: "ENDESGA",
    contactEmail: "ENDESGA@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 191,
    developerName: "Luscious Spirit Studios",
    contactEmail: "Luscious Spirit Studios@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 192,
    developerName: "ashwood",
    contactEmail: "ashwood@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 193,
    developerName: "SuppressiveFireGames",
    contactEmail: "SuppressiveFireGames@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 194,
    developerName: "saucygames",
    contactEmail: "saucygames@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 195,
    developerName: "Fayju",
    contactEmail: "Fayju@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 196,
    developerName: "B Studios",
    contactEmail: "B Studios@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 197,
    developerName: "catchandrelease",
    contactEmail: "catchandrelease@example.com",
    revenueSharePercentage: 0.11,
  },
  {
    id: 198,
    developerName: "Emerald Interactive Games",
    contactEmail: "Emerald Interactive Games@example.com",
    revenueSharePercentage: 0.11,
  },
];
