export const games: Array<string> = [
  "D/Generation HD",
  "G Prime Into The Rain",
  "Land Sliders",
  "Pixel Gear",
  "Gods and Idols",
  "Plague venue",
  "The Moon Sliver (itch)",
  "Red Entity",
  "HippiesVsCops",
  "They Came Through the Floor",
  "Fading Light: Descent",
  "The Book Ritual (Beta)",
  "Corner of the Club Simulator",
  "Serious Sam Fusion 2017 (beta)",
  "Intelligence: The 314th Clash!",
  "Que Sera Sera Demo",
  "Excelsior Phase One: Lysandia",
  "Space Escape",
  "Passing Through the Milky Way",
  "CORPUS100",
  "Thoughts",
  "Blasted Bots",
  "The Spaghetti Western Excavation",
  "Life is Feudal: Forest Village",
  "Legionwood 2: Rise of the Eternal's Realm",
  "Shape Master",
  "My World",
  "Toilet Tycoon (itch)",
  "Daddy",
  "The Spellbent Keep",
  "Circuit Breakers - Demo",
  "Toadie's Adventure",
  "A Near Dawn: Text Prototype",
  "Naval Action",
  "Purify",
  "Dog World",
  "Corra Snows",
  "Graveyard Birds (itch)",
  "Dark Rogue",
  "Bullet Time",
  "La Boîte Noire",
  "p o w e r ARM",
  "Oh No! Not Another J-RPG!",
  "Mages of Mystralia",
  "Emissary",
  "Zeus vs Monsters - Math Game",
  "herboto - LD37",
  "Fish Forever",
  "What Do We Eat for Dinner?",
  "Knight of Days",
  "Atomicollider",
  "Torch Cave (itch)",
  "Lapis Azurai",
  "SEUM: Speedrunners from Hell",
  "BLUMAN",
  "The Rootkit 1.1",
  "Horatio Salt and the Book of the Dead",
  "Gobbo goes adventure",
  "The Adventure",
  "Imperator Defence",
  "The Dream Self",
  "MAINFRAME",
  "Sunrise's Pact",
  "Slime Hunter",
  "Frog Climbers",
  "Choice Chamber (itch)",
  "DokiDoki fanmade",
  "Push & Pull",
  "Micro Island",
  "Grab Bag",
  "Wetwork (itch)",
  "Alleyway Cat Street",
  "World's Fastest Pizza (itch)",
  "The old lie",
  "Andoran Skye XD (itch)",
  "Operator Overload",
  "Aloisius",
  "Koji",
  "Escape Takashi",
  "Tender Was the Knight",
  "Stealth Fishing",
  "A Fraught Place",
  "Downside Up",
  "Gary SpringArms - Global Game Jam 17",
  "Cosmonet",
  "Sudden Strike 4",
  "VR Jurassic - Cardboard Park",
  "Freddy's Vr",
  "Frogbike",
  "Roguefort",
  "Lampette",
  "Scrapper Showdown",
  "No Danger Is Too Much",
  "Cosmic Chicken",
  "Captain Lycop: Invasion of the Heters",
  "Papai Noel is Dead",
  "Bollocks Biker",
  "The infamous @",
  "Verald Defense",
  "Dream Gazer",
  "Sepia and the Magical Book",
  "Giga Girl (itch)",
  "Flable Tip",
  "Star Wrecker Pre-Demo Demo",
  "Bullets!",
  "Riders of Asgard",
  "Comforting Sounds",
  "Super Capybros. 4 Advance",
  "Accurate Coastlines",
  "Road to Ruin",
  "BOB (TylerC)",
  "Zasa - An AI Story (itch)",
  "The Congress of Monsterdom",
  "Surf Shogun",
  "Mouse Boat",
  "Drawn In",
  "Mouse Playhouse",
  "Project: Scarf - Demo",
  "Trapped Demon",
  "2V Hoverbike (itch)",
  "Dual Wielded",
  "Dadoor",
  "Project Starship (itch)",
  "Super Skeleboy",
  "Ghostblasters: You Know Who to Call",
  "Dawn",
  "Aaron's Particle Space",
  "Tapsailing",
  "NULL",
  "Teh Stream: A Twizted Tale",
  "Coop Action Game Kit",
  "Roru",
  "NanoVirus",
  "Dungeon Scoundrel",
  "Just Feel",
  "MXGP3 - The Official Motocross Videogame",
  "Mirror Protocol",
  "Act of Mercy",
  "Rain Fall",
  "Bash Foxycut",
  "Pμcman",
  "Elemental Warrior",
  "Papi Commando - 100% Free Version PC !",
  "Humdrum",
  "Krampus Quest (itch)",
  "Matter (itch)",
  "Einlanzer",
  "Starjunk DSSR",
  "Foxglove",
  "GATE",
  "SnowNews",
  "Dinos Stole My Hyperdrive",
  "The Devil's Asshole",
  "The Little Prince",
  "Postman",
  "Mortal Online",
  "Willow (itch)",
  "Skull Dude",
  "Ultra6000",
  "Starfire Lords: Genesis",
  "Race against ferrum gigantes",
  "Rain Game (working title)",
  "Medieval Towns",
  "Scuttle at the Shuttle",
  "The Kleptocracy of Rodentia",
  "Lake Serene",
  "Of Guards And Thieves",
  "33 Grams",
  "Beat Trainer Deluxe",
  "Castle Chaos (itch)",
  "White Window",
  "Legends of Pizza Night",
  "DISCOCUBE",
  "Bumble Bots",
  "MagiTech City Blitz",
  "EEP Train Simulator Mission",
  "Port Blackfire",
  "Frost Final Demo",
  "Twirl",
  "The Rodinia Project (itch)",
  "onychophora",
  "BEARZERKERS (itch)",
  "Uncharted Dreams - Fate of the Miniatures",
  "FEAR OF VENGEANCE",
  "SteamedHams.exe",
  "The Attic's a Dungeon ?!",
  "Gravity Sketch VR",
  "Defend Felinearth (itch)",
  "Get Well Soon",
  "Magnetic",
  "BURROWED TIME",
  "Lovely Anemone",
  "Empress",
  "Blood Alloy: Reborn (itch)",
  "Dungeons & Clicks",
  "Amazing Frog?",
  "Soul of the Sword",
  "Star Billions",
  "Lil' Blue Buddy (itch)",
];
